namespace InvoiceService.Data;

public sealed class Invoice
{
    /// <summary>Generated by the service from a database sequence, e.g. FTR-000001. Primary key.</summary>
    public required string InvoiceNumber { get; set; }

    public required string CustomerCode { get; set; }

    public decimal Amount { get; set; }

    public required string Currency { get; set; }

    public DateOnly InvoiceDate { get; set; }

    /// <summary>One of <see cref="InvoiceStatus.Sent"/> or <see cref="InvoiceStatus.Failed"/>, enforced by a check constraint.</summary>
    public required string Status { get; set; }

    /// <summary>Reference returned by the ERP on 202; null while the invoice is not sent.</summary>
    public string? ErpReference { get; set; }

    /// <summary>Description of the error from the last send; null after a successful send.</summary>
    public string? LastError { get; set; }

    /// <summary>How many times the invoice was sent to the ERP (the first send included).</summary>
    public int SendAttemptCount { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    public DateTimeOffset UpdatedAt { get; set; }
}

public static class InvoiceStatus
{
    public const string Sent = "Gönderildi";
    public const string Failed = "Başarısız";
}

public static class InvoiceNumber
{
    public const string Prefix = "FTR-";

    /// <summary>FTR-000001 ... FTR-999999; grows past six digits instead of being truncated.</summary>
    public static string Format(long sequenceValue) => $"{Prefix}{sequenceValue:D6}";
}
