namespace InvoiceService.Domain.Invoices;

public sealed class Invoice
{
    /// <summary>Generated by the service from a database sequence, e.g. FTR-000001. Primary key.</summary>
    public required string InvoiceNumber { get; set; }

    public required string CustomerCode { get; set; }

    public decimal Amount { get; set; }

    public required string Currency { get; set; }

    public DateOnly InvoiceDate { get; set; }

    /// <summary>One of <see cref="InvoiceStatus"/>, enforced by a check constraint.</summary>
    public required string Status { get; set; }

    /// <summary>Reference returned by the ERP on 202; null while the invoice is not sent.</summary>
    public string? ErpReference { get; set; }

    /// <summary>The ERP's reason from an invoice.rejected event; null unless the invoice is Reddedildi.</summary>
    public string? RejectReason { get; set; }

    /// <summary>Description of the error from the last send; null after a successful send.</summary>
    public string? LastError { get; set; }

    /// <summary>
    /// How many attempts were made to get the invoice to the ERP over its whole life, resends included (never reset).
    /// An attempt POSTs the invoice, or, when the ERP may already have it, first asks the ERP and POSTs only if it does
    /// not; so this can be higher than the number of POSTs the ERP received.
    /// </summary>
    public int SendAttemptCount { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    public DateTimeOffset UpdatedAt { get; set; }
}

public static class InvoiceStatus
{
    /// <summary>Queued in erp_outbox, not sent to the ERP yet.</summary>
    public const string Pending = "Bekliyor";
    public const string Sent = "Gönderildi";

    /// <summary>The ERP reported invoice.received.</summary>
    public const string Processing = "İşleme Alındı";

    /// <summary>Final: the ERP reported invoice.approved; no event can change it.</summary>
    public const string Approved = "Onaylandı";

    /// <summary>Final: the ERP reported invoice.rejected (reason in reject_reason); no event can change it.</summary>
    public const string Rejected = "Reddedildi";

    /// <summary>Permanent: every attempt is used up (or the ERP rejected it); only a resend queues it again.</summary>
    public const string Failed = "Başarısız";

    public static readonly string[] All = [Pending, Sent, Processing, Approved, Rejected, Failed];
}

public static class InvoiceNumber
{
    public const string Prefix = "FTR-";

    /// <summary>FTR-000001 ... FTR-999999; grows past six digits instead of being truncated.</summary>
    public static string Format(long sequenceValue) => $"{Prefix}{sequenceValue:D6}";
}
