namespace ErpSimulator.Domain.Invoices;

public sealed class ErpInvoice
{
    public long Id { get; set; }

    /// <summary>Generated by the database from a sequence, e.g. ERP-00000042.</summary>
    public string ErpReference { get; set; } = null!;

    /// <summary>
    /// Not unique on purpose: by default the simulator does not protect against duplicates.
    /// Simulator:IdempotentInvoices turns the protection on in code (no unique index, so existing duplicates stay and
    /// the setting can be switched back).
    /// </summary>
    public required string InvoiceNumber { get; set; }

    public required string CustomerCode { get; set; }

    public decimal Amount { get; set; }

    public required string Currency { get; set; }

    public DateOnly InvoiceDate { get; set; }

    public DateTimeOffset ReceivedAt { get; set; }

    /// <summary>Behavior the simulator chose for the request that created this record.</summary>
    public required string Behavior { get; set; }

    public long RequestSequence { get; set; }
}
