namespace ErpSimulator.Data;

public sealed class ErpInvoice
{
    public long Id { get; set; }

    /// <summary>Generated by the database from a sequence, e.g. ERP-00000042.</summary>
    public string ErpReference { get; set; } = null!;

    /// <summary>Not unique on purpose: the simulator does not protect against duplicates.</summary>
    public required string InvoiceNumber { get; set; }

    public required string CustomerCode { get; set; }

    public decimal Amount { get; set; }

    public required string Currency { get; set; }

    public DateOnly InvoiceDate { get; set; }

    public DateTimeOffset ReceivedAt { get; set; }

    /// <summary>Behavior the simulator chose for the request that created this record.</summary>
    public required string Behavior { get; set; }

    public long RequestSequence { get; set; }
}
